repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-ast
          - id: check-toml
          - id: check-yaml
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: debug-statements
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [ --fix=lf ]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.4
      hooks:
        - id: ruff
          args: [ --output-format=github ]
        - id: ruff-format
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
            args: [ --check-untyped-defs ]
