[tool.black]
line-length = 120

[tool.isort]
line_length = 120
force_single_line = false
lexicographical = true
order_by_type = false
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
