name: ci-website
on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.11
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
