name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y tree poppler-utils
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_dev.txt
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
        env:
          PYTHONPATH: src/
        if: github.event_name == 'push'
