name: ci
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: astral-sh/ruff-action@v3
    - uses: pre-commit/action@v3.0.1
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libxml2 libxml2-dev libxslt1-dev
        python -m pip install --upgrade pip
        pip install pytest poetry lxml pyopenmensa deepl
    - name: Test with pytest
      run: pytest
      env:
        PYTHONPATH: src/
