name: publish

on:
    schedule:
        - cron: '0 9,21 * * MON-FRI'
        - cron: '0 21 * * SUN'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  sudo apt update -y
                  sudo apt install -y tree poppler-utils
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry config virtualenvs.create false
                  poetry install --no-interaction --no-ansi
            - name: Test with pytest
              run: pytest
              env:
                  PYTHONPATH: src/
              if: github.event_name == 'push'
            - name: Parse
              run: ./scripts/parse.sh
            - name: Deploy
              uses: docker://peaceiris/gh-pages:latest
              env:
                  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./dist
              with:
                  emptyCommits: false
                  keepFiles: true
              if: github.ref == 'refs/heads/master'
