name: publish

on:
    schedule:
        - cron: '0 9,21 * * MON-FRI'
        - cron: '0 21 * * SUN'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0 # Shalow clone, no history is needed

            - name: Setup uv
              uses: astral-sh/setup-uv@v4
              with:
                    enable-cache: true
                
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"

            - name: Install dependencies
              run: |
                  sudo apt update -y
                  sudo apt install -y tree poppler-utils
                  uv sync --all-extras --dev

            - name: Test with pytest
              run: uv run pytest
              env:
                  PYTHONPATH: src/
              if: github.event_name == 'push'

            - name: Parse
              run: ./scripts/parse.sh

            - name: Deploy
              uses: docker://peaceiris/gh-pages:latest
              env:
                  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./dist
              with:
                  emptyCommits: false
                  keepFiles: true
              if: github.ref == 'refs/heads/master'

            - name: Minimize uv cache
              run: uv cache prune --ci
